name: Build, Scan and Deploy
on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron: '0 0 * * *'
      
  workflow_dispatch:
  push:
    branches: 
      - master

env:
  DEV_REPO: ct-docker-dev.artifacts.cloudtrust.rocks
  PROD_REPO: ct-docker.artifacts.cloudtrust.rocks
  
jobs:
  ci:
    strategy:
      matrix:
        apps: ["logger-service", "authorization-service", "configuration-manager-service"]
    runs-on: ubuntu-latest
    steps:
      
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Pre-Build
        run: |
          echo "Pre-Build"
          echo $DEV_REPO
          echo $GITHUB_WORKSPACE
          
      # Build docker image      
      - name: build
        run: |
          echo "Hello ${{ matrix.apps }}"
          echo "- Hey build"
      
      # Scan docker image   
      - name: scan
        run: |
          echo "Hello ${{ matrix.apps }}"
          echo "- Hey scan"
      
      # Deploy docker image   
      - name: deploy
        run: |
          echo "Hello ${{ matrix.apps }}"
          echo "- Hey deploy"
      
      # Trigger spinnaker pipeline       
      - name: trigger
        run: |
          echo "Trigger spinnaker pipeline"
          
      - uses: jfrog/setup-jfrog-cli@v1
      - run: jfrog --version
          
