name: Build, Scan and Deploy
on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron: '*/10 * * * *'
  workflow_dispatch:


jobs:
  build:
    strategy:
      matrix:
        apps: ["logger-service", "authorization-service", "configuration-manager-service"]
    runs-on: ubuntu-latest
    steps:
      # Build docker image      
      - name: build
      - run: |
          echo "Hello ${{ matrix.apps }}"
          echo "- Hey build
      
      # Scan docker image   
      - name: scan
      - run: |
          echo "Hello ${{ matrix.apps }}"
          echo "- Hey scan"
      
      # Deploy docker image   
      - name: deploy
      - run: |
          echo "Hello ${{ matrix.apps }}"
          echo "- Hey deploy"
      
      # Trigger spinnaker pipeline       
      - name: trigger
      - run: |
          echo "Trigger spinnaker pipeline"
          
